//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use super::sea_orm_active_enums::DiscountType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "AppDiscount")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "appId", column_type = "Text")]
    pub app_id: String,
    #[sea_orm(column_type = "Text")]
    pub code: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_name = "discountType")]
    pub discount_type: DiscountType,
    #[sea_orm(column_name = "discountValue")]
    pub discount_value: i64,
    #[sea_orm(column_name = "maxUses")]
    pub max_uses: Option<i64>,
    #[sea_orm(column_name = "usedCount")]
    pub used_count: i64,
    #[sea_orm(column_name = "minPurchaseAmount")]
    pub min_purchase_amount: Option<i64>,
    #[sea_orm(column_name = "startsAt")]
    pub starts_at: DateTime,
    #[sea_orm(column_name = "expiresAt")]
    pub expires_at: Option<DateTime>,
    #[sea_orm(column_name = "isActive")]
    pub is_active: bool,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::app::Entity",
        from = "Column::AppId",
        to = "super::app::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    App,
    #[sea_orm(has_many = "super::app_purchase::Entity")]
    AppPurchase,
}

impl Related<super::app::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::App.def()
    }
}

impl Related<super::app_purchase::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppPurchase.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
