//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use super::sea_orm_active_enums::PurchaseStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "AppPurchase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "userId", column_type = "Text")]
    pub user_id: String,
    #[sea_orm(column_name = "appId", column_type = "Text")]
    pub app_id: String,
    #[sea_orm(column_name = "pricePaid")]
    pub price_paid: i64,
    #[sea_orm(column_name = "originalPrice")]
    pub original_price: i64,
    #[sea_orm(column_name = "discountAmount")]
    pub discount_amount: i64,
    #[sea_orm(column_name = "discountId", column_type = "Text", nullable)]
    pub discount_id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub currency: String,
    #[sea_orm(column_name = "stripeSessionId", column_type = "Text")]
    pub stripe_session_id: String,
    #[sea_orm(column_name = "stripePaymentIntentId", column_type = "Text", nullable)]
    pub stripe_payment_intent_id: Option<String>,
    pub status: PurchaseStatus,
    #[sea_orm(column_name = "completedAt")]
    pub completed_at: Option<DateTime>,
    #[sea_orm(column_name = "refundedAt")]
    pub refunded_at: Option<DateTime>,
    #[sea_orm(column_name = "refundReason", column_type = "Text", nullable)]
    pub refund_reason: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::app::Entity",
        from = "Column::AppId",
        to = "super::app::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    App,
    #[sea_orm(
        belongs_to = "super::app_discount::Entity",
        from = "Column::DiscountId",
        to = "super::app_discount::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    AppDiscount,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::app::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::App.def()
    }
}

impl Related<super::app_discount::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppDiscount.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
