//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use super::sea_orm_active_enums::SolutionPricingTier;
use super::sea_orm_active_enums::SolutionStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "SolutionRequest")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub email: String,
    #[sea_orm(column_type = "Text")]
    pub company: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_name = "applicationType", column_type = "Text")]
    pub application_type: String,
    #[sea_orm(column_name = "dataSecurity", column_type = "Text")]
    pub data_security: String,
    #[sea_orm(column_name = "exampleInput", column_type = "Text")]
    pub example_input: String,
    #[sea_orm(column_name = "expectedOutput", column_type = "Text")]
    pub expected_output: String,
    #[sea_orm(column_name = "userCount", column_type = "Text")]
    pub user_count: String,
    #[sea_orm(column_name = "userType", column_type = "Text")]
    pub user_type: String,
    #[sea_orm(column_name = "technicalLevel", column_type = "Text")]
    pub technical_level: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub timeline: Option<String>,
    #[sea_orm(column_name = "additionalNotes", column_type = "Text", nullable)]
    pub additional_notes: Option<String>,
    #[sea_orm(column_name = "pricingTier")]
    pub pricing_tier: SolutionPricingTier,
    #[sea_orm(column_name = "paidDeposit")]
    pub paid_deposit: bool,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub files: Option<Json>,
    #[sea_orm(column_name = "storageKey", column_type = "Text", nullable)]
    pub storage_key: Option<String>,
    pub status: SolutionStatus,
    #[sea_orm(
        column_name = "stripeCheckoutSessionId",
        column_type = "Text",
        nullable,
        unique
    )]
    pub stripe_checkout_session_id: Option<String>,
    #[sea_orm(
        column_name = "stripePaymentIntentId",
        column_type = "Text",
        nullable,
        unique
    )]
    pub stripe_payment_intent_id: Option<String>,
    #[sea_orm(
        column_name = "stripeSetupIntentId",
        column_type = "Text",
        nullable,
        unique
    )]
    pub stripe_setup_intent_id: Option<String>,
    #[sea_orm(column_name = "totalCents")]
    pub total_cents: i64,
    #[sea_orm(column_name = "depositCents")]
    pub deposit_cents: i64,
    #[sea_orm(column_name = "remainderCents")]
    pub remainder_cents: i64,
    pub priority: bool,
    #[sea_orm(column_name = "adminNotes", column_type = "Text", nullable)]
    pub admin_notes: Option<String>,
    #[sea_orm(column_name = "assignedTo", column_type = "Text", nullable)]
    pub assigned_to: Option<String>,
    #[sea_orm(column_name = "deliveredAt")]
    pub delivered_at: Option<DateTime>,
    #[sea_orm(column_name = "trackingToken", column_type = "Text", unique)]
    pub tracking_token: String,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::solution_log::Entity")]
    SolutionLog,
}

impl Related<super::solution_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SolutionLog.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
