//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use super::sea_orm_active_enums::UserStatus;
use super::sea_orm_active_enums::UserTier;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "User")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "stripeId", column_type = "Text", nullable, unique)]
    pub stripe_id: Option<String>,
    #[sea_orm(column_name = "trackingId", column_type = "Text", nullable, unique)]
    pub tracking_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub email: Option<String>,
    #[sea_orm(column_type = "Text", nullable, unique)]
    pub username: Option<String>,
    #[sea_orm(
        column_name = "preferredUsername",
        column_type = "Text",
        nullable,
        unique
    )]
    pub preferred_username: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub avatar: Option<String>,
    #[sea_orm(
        column_name = "additionalInformation",
        column_type = "JsonBinary",
        nullable
    )]
    pub additional_information: Option<Json>,
    pub permission: i64,
    #[sea_orm(column_name = "acceptedTermsVersion", column_type = "Text", nullable)]
    pub accepted_terms_version: Option<String>,
    #[sea_orm(column_name = "tutorialCompleted")]
    pub tutorial_completed: bool,
    pub status: UserStatus,
    pub tier: UserTier,
    #[sea_orm(column_name = "totalSize")]
    pub total_size: i64,
    #[sea_orm(column_name = "totalLLMPrice")]
    pub total_llm_price: i64,
    #[sea_orm(column_name = "totalEmbeddingPrice")]
    pub total_embedding_price: i64,
    #[sea_orm(column_name = "llmPriceTrackingMonth", column_type = "Text", nullable)]
    pub llm_price_tracking_month: Option<String>,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::app_purchase::Entity")]
    AppPurchase,
    #[sea_orm(has_many = "super::comment::Entity")]
    Comment,
    #[sea_orm(has_many = "super::embedding_usage_tracking::Entity")]
    EmbeddingUsageTracking,
    #[sea_orm(has_many = "super::execution_run::Entity")]
    ExecutionRun,
    #[sea_orm(has_many = "super::execution_usage_tracking::Entity")]
    ExecutionUsageTracking,
    #[sea_orm(has_many = "super::feedback::Entity")]
    Feedback,
    #[sea_orm(has_many = "super::invitation::Entity")]
    Invitation,
    #[sea_orm(has_many = "super::join_queue::Entity")]
    JoinQueue,
    #[sea_orm(has_many = "super::llm_usage_tracking::Entity")]
    LlmUsageTracking,
    #[sea_orm(has_many = "super::membership::Entity")]
    Membership,
    #[sea_orm(has_many = "super::notification::Entity")]
    Notification,
    #[sea_orm(has_many = "super::pat::Entity")]
    Pat,
    #[sea_orm(has_many = "super::profile::Entity")]
    Profile,
    #[sea_orm(has_many = "super::publication_log::Entity")]
    PublicationLog,
    #[sea_orm(has_many = "super::publication_request::Entity")]
    PublicationRequest,
    #[sea_orm(has_many = "super::transaction::Entity")]
    Transaction,
    #[sea_orm(has_many = "super::wasm_package_author::Entity")]
    WasmPackageAuthor,
    #[sea_orm(has_many = "super::wasm_package_review::Entity")]
    WasmPackageReview,
}

impl Related<super::app_purchase::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppPurchase.def()
    }
}

impl Related<super::comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comment.def()
    }
}

impl Related<super::embedding_usage_tracking::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EmbeddingUsageTracking.def()
    }
}

impl Related<super::execution_run::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExecutionRun.def()
    }
}

impl Related<super::execution_usage_tracking::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExecutionUsageTracking.def()
    }
}

impl Related<super::feedback::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Feedback.def()
    }
}

impl Related<super::invitation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Invitation.def()
    }
}

impl Related<super::join_queue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JoinQueue.def()
    }
}

impl Related<super::llm_usage_tracking::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LlmUsageTracking.def()
    }
}

impl Related<super::membership::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Membership.def()
    }
}

impl Related<super::notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notification.def()
    }
}

impl Related<super::pat::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pat.def()
    }
}

impl Related<super::profile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Profile.def()
    }
}

impl Related<super::publication_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PublicationLog.def()
    }
}

impl Related<super::publication_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PublicationRequest.def()
    }
}

impl Related<super::transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transaction.def()
    }
}

impl Related<super::wasm_package_author::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WasmPackageAuthor.def()
    }
}

impl Related<super::wasm_package_review::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WasmPackageReview.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
