//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use super::sea_orm_active_enums::WasmPackageStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "WasmPackage")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    #[sea_orm(column_type = "Text")]
    pub version: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub license: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub homepage: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub repository: Option<String>,
    pub keywords: Option<Vec<String>>,
    pub status: WasmPackageStatus,
    pub verified: bool,
    #[sea_orm(column_name = "downloadCount")]
    pub download_count: i64,
    #[sea_orm(column_name = "wasmPath", column_type = "Text")]
    pub wasm_path: String,
    #[sea_orm(column_name = "wasmHash", column_type = "Text")]
    pub wasm_hash: String,
    #[sea_orm(column_name = "wasmSize")]
    pub wasm_size: i64,
    #[sea_orm(column_type = "JsonBinary")]
    pub nodes: Json,
    #[sea_orm(column_type = "JsonBinary")]
    pub permissions: Json,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(column_name = "publishedAt")]
    pub published_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::wasm_package_author::Entity")]
    WasmPackageAuthor,
    #[sea_orm(has_many = "super::wasm_package_review::Entity")]
    WasmPackageReview,
    #[sea_orm(has_many = "super::wasm_package_version::Entity")]
    WasmPackageVersion,
}

impl Related<super::wasm_package_author::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WasmPackageAuthor.def()
    }
}

impl Related<super::wasm_package_review::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WasmPackageReview.def()
    }
}

impl Related<super::wasm_package_version::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WasmPackageVersion.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
