//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use super::sea_orm_active_enums::WasmPackageStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(schema_name = "public", table_name = "WasmPackageVersion")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "packageId", column_type = "Text")]
    pub package_id: String,
    #[sea_orm(column_type = "Text")]
    pub version: String,
    #[sea_orm(column_name = "wasmPath", column_type = "Text")]
    pub wasm_path: String,
    #[sea_orm(column_name = "wasmHash", column_type = "Text")]
    pub wasm_hash: String,
    #[sea_orm(column_name = "wasmSize")]
    pub wasm_size: i64,
    #[sea_orm(column_name = "releaseNotes", column_type = "Text", nullable)]
    pub release_notes: Option<String>,
    #[sea_orm(column_name = "minFlowLikeVersion", column_type = "Text", nullable)]
    pub min_flow_like_version: Option<String>,
    pub yanked: bool,
    pub status: WasmPackageStatus,
    #[sea_orm(column_name = "publishedAt")]
    pub published_at: DateTime,
    #[sea_orm(column_name = "approvedAt")]
    pub approved_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::wasm_package::Entity",
        from = "Column::PackageId",
        to = "super::wasm_package::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    WasmPackage,
}

impl Related<super::wasm_package::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WasmPackage.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
