-- Oracle test data initialization
-- This script runs automatically when the container starts

-- Create sample tables
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(255) UNIQUE NOT NULL,
    age NUMBER(3),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active NUMBER(1) DEFAULT 1
);

CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES users(id),
    product_name VARCHAR2(255) NOT NULL,
    quantity NUMBER NOT NULL,
    price NUMBER(10, 2) NOT NULL,
    order_date DATE DEFAULT SYSDATE,
    status VARCHAR2(50) DEFAULT 'pending'
);

CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    category VARCHAR2(100),
    price NUMBER(10, 2) NOT NULL,
    stock NUMBER DEFAULT 0,
    description CLOB
);

-- Insert test data
INSERT INTO users (name, email, age, is_active) VALUES ('Alice Johnson', 'alice@example.com', 28, 1);
INSERT INTO users (name, email, age, is_active) VALUES ('Bob Smith', 'bob@example.com', 35, 1);
INSERT INTO users (name, email, age, is_active) VALUES ('Carol White', 'carol@example.com', 42, 0);
INSERT INTO users (name, email, age, is_active) VALUES ('David Brown', 'david@example.com', 31, 1);
INSERT INTO users (name, email, age, is_active) VALUES ('Eve Davis', 'eve@example.com', 25, 1);

INSERT INTO products (name, category, price, stock, description) VALUES ('Laptop Pro', 'Electronics', 1299.99, 50, 'High-performance laptop');
INSERT INTO products (name, category, price, stock, description) VALUES ('Wireless Mouse', 'Electronics', 29.99, 200, 'Ergonomic wireless mouse');
INSERT INTO products (name, category, price, stock, description) VALUES ('Office Chair', 'Furniture', 249.99, 30, 'Comfortable office chair');
INSERT INTO products (name, category, price, stock, description) VALUES ('Desk Lamp', 'Furniture', 49.99, 100, 'LED desk lamp');
INSERT INTO products (name, category, price, stock, description) VALUES ('Coffee Mug', 'Kitchen', 12.99, 500, 'Ceramic coffee mug');

INSERT INTO orders (user_id, product_name, quantity, price, status) VALUES (1, 'Laptop Pro', 1, 1299.99, 'completed');
INSERT INTO orders (user_id, product_name, quantity, price, status) VALUES (1, 'Wireless Mouse', 2, 59.98, 'completed');
INSERT INTO orders (user_id, product_name, quantity, price, status) VALUES (2, 'Office Chair', 1, 249.99, 'shipped');
INSERT INTO orders (user_id, product_name, quantity, price, status) VALUES (3, 'Desk Lamp', 3, 149.97, 'pending');
INSERT INTO orders (user_id, product_name, quantity, price, status) VALUES (4, 'Coffee Mug', 5, 64.95, 'completed');
INSERT INTO orders (user_id, product_name, quantity, price, status) VALUES (5, 'Laptop Pro', 1, 1299.99, 'processing');

COMMIT;

-- Create view for testing
CREATE VIEW user_orders AS
SELECT
    u.id as user_id,
    u.name as user_name,
    u.email,
    COUNT(o.id) as order_count,
    NVL(SUM(o.price), 0) as total_spent
FROM users u
LEFT JOIN orders o ON u.id = o.user_id
GROUP BY u.id, u.name, u.email;

-- Gather statistics
EXEC DBMS_STATS.GATHER_TABLE_STATS(USER, 'USERS');
EXEC DBMS_STATS.GATHER_TABLE_STATS(USER, 'ORDERS');
EXEC DBMS_STATS.GATHER_TABLE_STATS(USER, 'PRODUCTS');
